In [ ]:
## check numpy version
import numpy as np
# 1d . 2d , 3d , 4d 
np.__version__

'2.1.1'

In [ ]:
lst = [1,2,3,4,5]
arl = np.array(lst)
print(type(arl))
arl

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [16]:
arl = np.array([1,2,"3",4,5])
arl

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [24]:
lst = [x for x in  range(1 , 6)]
arl = np.array(lst)
lst

[1, 2, 3, 4, 5]

In [26]:
ar2 = np.arange(1,11)
ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
ar3 = np.ones(5)
ar3

array([1., 1., 1., 1., 1.])

In [34]:
ar4 = np.zeros(5)
ar4

array([0., 0., 0., 0., 0.])

# 2-d array

In [36]:
ar5 = np.zeros((2,3))
ar5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
ar6 = np.ones((8,9))
ar6

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [48]:
ar7 = np.linspace(1,10,5)
ar7

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
## 1-d array to 2 d array

ar8 = np.arange(1,31).reshape(5,6) 
ar8

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [58]:
ar9 = np.random.randint(1,100,10)
ar9

array([ 4, 30, 88, 87, 78, 13, 58, 88, 46, 29], dtype=int32)

In [59]:
arr = np.random.random(10)
arr

array([0.36933804, 0.42047079, 0.80598441, 0.93454296, 0.07320695,
       0.42486222, 0.53573553, 0.06220815, 0.4867934 , 0.21592358])

In [63]:
matrix = np.arange(1,61).reshape(10,6)
matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [66]:
matrix = np.arange(1,61).reshape(10,6)
matrix.shape
matrix.dtype
matrix.size
matrix.ndim


2

In [72]:
# Convert multidimension array in 1 d
matrix = np.arange(1,61).reshape(10,6)
print(matrix)

matrix.ravel()
matrix.flatten()

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [75]:
## TRANSPOSE OF A MATRIX
matrix = np.arange(1,61).reshape(10,6)
print(matrix.shape)
M2 = matrix.T.shape
M2

(10, 6)


(6, 10)

## INDEXING & SLICING

In [76]:

ar2 = np.arange(1,11)
print(ar2[5])


6


In [78]:
ar2 = np.arange(1,11)
print(ar2[-4:-2])

[7 8]


In [98]:
## indexing and slicing for 2d array
# Indexing -- [row,start:row end: rowskip,col start:colend:skip]
matrix = np.arange(1,61).reshape(12,5)
# print(matrix)

print(matrix[3:4,2:3])

[[18]]


In [105]:
matrix[9:10,4:5][0][0]
matrix[::-1,::-1]

array([[60, 59, 58, 57, 56],
       [55, 54, 53, 52, 51],
       [50, 49, 48, 47, 46],
       [45, 44, 43, 42, 41],
       [40, 39, 38, 37, 36],
       [35, 34, 33, 32, 31],
       [30, 29, 28, 27, 26],
       [25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [ ]:
##3d array
arr11 = np.arange(225).reshape(3,15,5)
arr11

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [120]:
#slicing in 3rd array
# syntax
# [table start:table end :table skip,row start : row end : row skip : col start : col end : col skip]
arr11[0:,1:4,2:4]

array([[[  7,   8],
        [ 12,  13],
        [ 17,  18]],

       [[ 82,  83],
        [ 87,  88],
        [ 92,  93]],

       [[157, 158],
        [162, 163],
        [167, 168]]])